#!/bin/bash

script_path=$(cd $(dirname "${BASH_SOURCE[0]}") ; pwd)

virtualenv ${script_path}/../.venv
. ${script_path}/../.venv/bin/activate

# Python Imaging Library (PIL)
pip install -r ${script_path}/../requirements.txt
